'use strict';
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var sinaWeiboSchema = new Schema({
    //access info
    access_token: {type: String},
    uid: {type: String},
    expires_in: {type: String},
    expireDate: {type: Date},
    //weibo info
    id: {type: Number},
    idstr: {type: String},
    screen_name: {type: String},
    name: {type: String},
    province: {type: String},
    city: {type: String},
    location: {type: String},
    description: {type: String},
    url: {type: String},
    profile_image_url: {type: String},
    cover_image_phone: {type: String},
    profile_url: {type: String},
    domain: {type: String},
    weihao: {type: String},
    gender: {type: String},
    followers_count: {type: Number},
    friends_count: {type: Number},
    pagefriends_count: {type: Number},
    statuses_count: {type: Number},
    favourites_count: {type: Number},
    created_at: {type: Date},
    following: {type: Boolean},
    allow_all_act_msg: {type: Boolean},
    geo_enabled: {type: Boolean},
    verified: {type: Boolean},
    verified_type: {type: Number},
    remark: {type: String},
    ptype: {type: Number},
    allow_all_comment: {type: Boolean},
    avatar_large: {type: String},
    avatar_hd: {type: String},
    verified_reason: {type: String},
    verified_trade: {type: String},
    verified_reason_url: {type: String},
    verified_source: {type: String},
    verified_source_url: {type: String},
    verified_state: {type: Number},
    verified_level: {type: Number},
    verified_reason_modified: {type: String},
    verified_contact_name: {type: String},
    verified_contact_email: {type: String},
    verified_contact_mobile: {type: String},
    follow_me: {type: Boolean},
    online_status: {type: Number},
    bi_followers_count: {type: Number},
    lang: {type: String},
    star: {type: Number},
    mbtype: {type: Number},
    mbrank: {type: Number},
    block_word: {type: Number},
    block_app: {type: Number},
    ability_tags: {type: String},
    credit_score: {type: Number},
    user_ability: {type: Number},
    urank: {type: Number},
    //reference user model
    user: {type: Schema.Types.ObjectId, ref: 'Users'}
});
var sinaWeibo = mongoose.model('SinaWeibo', sinaWeiboSchema);
module.exports = sinaWeibo;
